MySystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Students/',include('Students.urls',namespace='Students')),
    path('Predict/',include('Predict.urls',namespace='Predict')),
    path('account/',include('account.urls',namespace='account')),
]

Predict/urls.py
from django.urls import path
from . import views

app_name='Predict'

urlpatterns = [
    path('',views.grades_list,name='grades_list'),
    path('g_add/',views.add_grades,name='add_grades'),
    path('result/',views.pre_result,name='pre_result'),
]

Students/urls.py
from django.urls import path
from . import views
import account.urls

app_name = 'Students'

urlpatterns = [
    path('', views.Stu_List, name='Stu_List'),
    path('<str:SN>/<str:CN>/', views.Stu_Detail, name='Stu_Detail'),
    path('add/', views.add_student, name='add_student'), 
    path('delete/<str:SN>/<str:CN>/',views.delete_student,name='delete_student'),
]

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='account'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('',views.index,name='index'),
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('register/',views.register,name='register'),
    path('edit/',views.edit,name='edit'),
]

account/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Teacher(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    teacher_id=models.CharField(max_length=50)

    def __str__(self):
        return self.user.username
    
class Classes(models.Model):
    Class_Number_id = models.CharField(max_length=50, primary_key=True)  # 班级号作为主键
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)  # 使用 ForeignKey 关联老师表

    def __str__(self):
        return self.Class_Number_id

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Teacher,Classes

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password=forms.CharField(label='Password',widget=forms.PasswordInput)
    password2=forms.CharField(label='Repeat Password',widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=('username','email')

    def clean_password2(self):
        cd=self.cleaned_data
        if cd['password']!=cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']
    
class UserEditForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','email')

class TeacherEditForm(forms.ModelForm):
    class Meta:
        model=Teacher
        fields=('teacher_id',)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate,login
from .forms import LoginForm,UserRegistrationForm,UserEditForm,TeacherEditForm
from .models import Teacher
from django.contrib import messages

# Create your views here.
from django.shortcuts import redirect

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # 登录成功后重定向到 index 视图
                    return redirect('index')
                else:
                    return HttpResponse('无效账户')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

                
from django.contrib.auth.decorators import login_required
@login_required
def index(request):
    return render(request,
                  'account/index.html',
                  {'section': 'index'})

def register(request):
    if request.method=='POST':
        user_form=UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Teacher.objects.create(user=new_user)
            return render(request,'account/register_done.html',{'new_user':new_user})
    else:
        user_form=UserRegistrationForm()
    return render(request,'account/register.html',{'user_form':user_form})

@login_required
def edit(request):
    if request.method=='POST':
        user_form=UserEditForm(instance=request.user,data=request.POST)
        teacher_form=TeacherEditForm(instance=request.user.teacher,data=request.POST,files=request.FILES)
        if user_form.is_valid() and teacher_form.is_valid():
            user_form.save()
            teacher_form.save()
            messages.success(request,'更改成功')
        else:
            messages.error(request,'出错了！')
    else:
        user_form=UserEditForm(instance=request.user)
        teacher_form=TeacherEditForm(instance=request.user.teacher)
    return render(request,'account/edit.html',{'user_form':user_form,'teacher_form':teacher_form})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <span class="logo">面向教育的异常检测</span>
            {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "index" %}class="selected"{% endif %}>
                    <a href="{% url 'account:index' %}">个人信息</a>
                </li>
                <li {% if section == "Stu_List" %}class="selected"{% endif %}>
                    <a href="{% url 'Students:Stu_List' %}">KMeans</a>
                </li>
                <li {% if section == "grades_list" %}class="selected"{% endif %}>
                    <a href="{% url 'Predict:grades_list' %}">RNN</a>
                </li>
            </ul>
            {% endif %}
            <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.username }},
                <!--<a href="{% url "account:logout" %}">Logout</a>-->
                <form action="{% url 'account:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="transparent-button" type="submit">登出</button>
                </form>             
            {% else %}
                <a href="{% url "account:login" %}">Log-in</a>
            {% endif %}
            </span>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>