MySystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Students/',include('Students.urls',namespace='Students')),
    path('Predict/',include('Predict.urls',namespace='Predict')),
    path('account/',include('account.urls',namespace='account')),
]

Predict/urls.py
from django.urls import path
from . import views

app_name='Predict'

urlpatterns = [
    path('',views.grades_list,name='grades_list'),
    path('g_add/',views.add_grades,name='add_grades'),
    path('result/',views.pre_result,name='pre_result'),
]

Predict/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Prediction(models.Model):
    test_time=models.DateTimeField(primary_key=True)
    avg_grade=models.FloatField()

Predict/views.py
from django.shortcuts import render,redirect
from .models import Prediction
from django.contrib.auth.decorators import login_required
from .rnn import draw1,draw2

# Create your views here.

@login_required
def grades_list(request):
    grades=Prediction.objects.order_by('test_time')
    return render(request,'Pre/adding.html',{'grades':grades,'section':'grades_list'})

@login_required
def add_grades(request):
    if request.method == 'POST':
        # 如果表单被提交，处理表单数据
        test_time = request.POST.get('test_time')
        avg_grade = request.POST.get('avg_grade')
        
        # 创建grade对象并保存到数据库
        Prediction.objects.create(
            test_time=test_time,
            avg_grade=avg_grade,
        )
        # 重定向到grades列表页面
        return redirect('Predict:grades_list')
    else:
        # 如果是GET请求，返回空的表单
        return render(request, 'Predict/adding.html')

@login_required
def pre_result(request):
    image_path1 = draw1()
    image_path2 = draw2()
    
    # 将图片路径添加到上下文数据中
    context = {'image_path1': image_path1, 'image_path2': image_path2}
    
    return render(request, 'Pre/result.html', context)

Predict/templates/Pre/adding.html
{% extends 'base.html' %}
{% load static %}

{% block title %}RNN Prediction{% endblock %}

{% block content %}

<link href="{% static "list.css" %}" rel="stylesheet">
<h1>成绩单</h1>

<p><a href="{% url "Predict:pre_result" %}">查看结果</a></p>

<div class="container">
    <div class="left">
        <div class="table-container">
            <table class="grades-table">
                <thead>
                    <tr>
                        <th>考试时间</th>
                        <th>平均成绩</th>
                    </tr>
                </thead>
                <tbody>
                    {% for grade in grades %}
                    <tr>
                        <td>{{ grade.test_time|date:"Y年m月" }}</td>
                        <td>{{ grade.avg_grade }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="right">
        <h2>添加成绩</h2>
        <!-- 添加成绩表单 -->
        <form method="post" action="{% url 'Predict:add_grades' %}">
            {% csrf_token %}
            <div class="add-grades-form">
                <label for="test_time">test_time:</label>
                <input type="date" name="test_time" id="test_time" title="测试时间">
                <label for="avg_grade">avg_grade:</label>
                <input type="text" name="avg_grade" id="avg_grade" title="测试平均成绩">
            </div>
            <p><input type="submit" value="添加"></p>
        </form>
    </div>
</div>
{% endblock %}

Predict/templates/Pre/result.html
{% extends 'base.html' %}
{% load static %}

{% block title %}RNN Prediction{% endblock %}

{% block content %}

<h1>预测结果</h1>

<div>
    <img src="{{image_path1}}" alt="Prediction1">
</div>

<div>
    <img src="{{image_path2}}" alt="Prediction2">
</div>

{% endblock %}