MySystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Students/',include('Students.urls',namespace='Students')),
    path('Predict/',include('Predict.urls',namespace='Predict')),
    path('account/',include('account.urls',namespace='account')),
]

Predict/urls.py
from django.urls import path
from . import views

app_name='Predict'

urlpatterns = [
    path('',views.grades_list,name='grades_list'),
    path('g_add/',views.add_grades,name='add_grades'),
    path('result/',views.pre_result,name='pre_result'),
]

Students/urls.py
from django.urls import path
from . import views
import account.urls

app_name = 'Students'

urlpatterns = [
    path('', views.Stu_List, name='Stu_List'),
    path('<str:SN>/<str:CN>/', views.Stu_Detail, name='Stu_Detail'),
    path('add/', views.add_student, name='add_student'), 
    path('delete/<str:SN>/<str:CN>/',views.delete_student,name='delete_student'),
]

Students/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import redirect, render
from account.models import Classes

# Create your models here.
class Stu_Info(models.Model):
    Stu_Number = models.CharField(max_length=50)
    Class_Number = models.ForeignKey(Classes, on_delete=models.CASCADE)
    Medu = models.IntegerField()  # Mother's education level
    Fedu = models.IntegerField()  # Father's education level
    traveltime = models.IntegerField()  # Home to school travel time
    studytime = models.IntegerField()  # Weekly study time
    failures = models.IntegerField()  # Number of past class failures
    famrel = models.IntegerField()  # Quality of family relationships
    freetime = models.IntegerField()  # Free time after school
    goout = models.IntegerField()  # Going out with friends
    healths = models.IntegerField()  # Current health status
    absences = models.IntegerField()  # Number of school absences
    G1 = models.IntegerField(null=True, default=None)
  # First period grade
    G2 = models.IntegerField(null=True, default=None)  # Second period grade
    G3 = models.IntegerField()  # Final grade

    def get_absolute_url(self):
        return reverse('Students:Stu_Detail', args=[self.Stu_Number, self.Class_Number])

    
    

Students/views.py
from django.shortcuts import redirect, render,get_object_or_404
from .models import Stu_Info
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .km import generate_kmeans_plot
from account.views import index

# Create your views here.

from django.contrib.auth.decorators import login_required
@login_required
def Stu_List(request):
    object_list = Stu_Info.objects.order_by('Class_Number_id', 'Stu_Number')

    # 获取搜索框中的学生学号
    search_query = request.GET.get('search', '')

    # 如果搜索框中有内容，则进行过滤
    if search_query:
        object_list = object_list.filter(Stu_Number__icontains=search_query)

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')
    try:
        stus = paginator.page(page)
    except PageNotAnInteger:
        stus = paginator.page(1)
    except EmptyPage:
        stus = paginator.page(paginator.num_pages)
    return render(request, 'Students/stu_info/list.html', {'page': page, 'stus': stus, 'section':'Stu_List'})

@login_required
def Stu_Detail(request, SN, CN):
    stu = get_object_or_404(Stu_Info, Stu_Number=SN, Class_Number_id=CN)
    
    # 调用K均值聚类算法函数并获取生成的图片文件路径和异常值检测结果
    image_path, is_outlier = generate_kmeans_plot(stu.id)
    
    # 将图片路径和异常值检测结果添加到上下文数据中
    context = {'stu': stu, 'image_path': image_path, 'is_outlier': is_outlier}
    
    return render(request, 'Students/stu_info/detail.html', context)

@login_required
def add_student(request):
    if request.method == 'POST':
        # 如果表单被提交，处理表单数据
        stu_number = request.POST.get('Stu_Number')
        class_number = request.POST.get('Class_Number_id')
        medu = request.POST.get('Medu')
        fedu = request.POST.get('Fedu')
        traveltime = request.POST.get('traveltime')
        studytime = request.POST.get('studytime')
        failures = request.POST.get('failures')
        famrel = request.POST.get('famrel')
        freetime = request.POST.get('freetime')
        goout = request.POST.get('goout')
        healths = request.POST.get('healths')
        absences = request.POST.get('absences')
        g1 = request.POST.get('G1')
        g2 = request.POST.get('G2')
        g3 = request.POST.get('G3')
        
        # 创建学生对象并保存到数据库
        Stu_Info.objects.create(
            Stu_Number=stu_number,
            Class_Number_id=class_number,
            Medu=medu,
            Fedu=fedu,
            traveltime=traveltime,
            studytime=studytime,
            failures=failures,
            famrel=famrel,
            freetime=freetime,
            goout=goout,
            healths=healths,
            absences=absences,
            G1=g1,
            G2=g2,
            G3=g3,
            # 设置其他学生信息字段
        )
        # 重定向到学生列表页面
        return redirect('Students:Stu_List')
    else:
        # 如果是GET请求，返回空的表单
        return render(request, 'Students/list.html')

@login_required
def delete_student(request, SN, CN):
    stu = get_object_or_404(Stu_Info, Stu_Number=SN, Class_Number_id=CN)
    stu.delete()
    return redirect('Students:Stu_List')

Students/templates/Students/stu_info/detail.html
{% extends 'Students/base.html' %}

{% block title %}Student Detail{% endblock %}

{% block content %}
    <h1>Kmeans聚类</h1>
    <p><strong>Class Number:</strong> {{ stu.Class_Number_id }}</p>
    <p><strong>Student Number:</strong> {{ stu.Stu_Number }}</p>
    <div>
    <img src="{{image_path}}" alt="K-means Clustering Image">
    </div>
    {% if is_outlier %}
    <p style="color: red; font-weight: bold;">该学生异常</p>
    {% else %}
    <p style="color: green; font-weight: bold;">该学生不存在异常</p>
    {% endif %}

    <!-- 删除按钮 -->
    <form action="{% url 'Students:delete_student' stu.Stu_Number stu.Class_Number_id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="删除该学生">
    </form>
    
{% endblock %}

Students/templates/Students/stu_info/list.html
{% extends 'Students/base.html' %}
{% load static %}

{% block title %}Student List{% endblock %}

{% block content %}

<link href="{% static "list.css" %}" rel="stylesheet">
<h1>学生列表</h1>

<div class="search-container">
    <form id="search-form" method="GET" action="">
        <input type="text" id="search-input" name="search" placeholder="输入学生学号...">
        <button type="submit">查询</button>
        <button type="button" onclick="clearSearch()">清除</button>
    </form>
</div>

<script>
    function clearSearch() {
        document.getElementById("search-input").value = "";
        document.getElementById("search-form").submit();
    }
</script>

<div class="table-container">
    <table class="student-table">
        <thead>
            <tr>
                <th>学生学号</th>
                <th>班级号</th>
                <th>母亲教育程度</th>
                <th>父亲教育程度</th>
                <th>上学通勤时间</th>
                <th>每周学习时间</th>
                <th>失败次数</th>
                <th>家庭关系</th>
                <th>自由时间</th>
                <th>出门时间</th>
                <th>健康状况</th>
                <th>缺勤次数</th>
                <th>G3</th>
            </tr>
        </thead>
        <tbody>
            {% for stu in stus %}
                <tr>
                    <td><a href="{{ stu.get_absolute_url }}">{{ stu.Stu_Number }}</a></td>
                    <td>{{ stu.Class_Number_id }}</td>
                    <td>{{ stu.Medu }}</td>
                    <td>{{ stu.Fedu }}</td>
                    <td>{{ stu.traveltime }}</td>
                    <td>{{ stu.studytime }}</td>
                    <td>{{ stu.failures }}</td>
                    <td>{{ stu.famrel }}</td>
                    <td>{{ stu.freetime }}</td>
                    <td>{{ stu.goout }}</td>
                    <td>{{ stu.healths }}</td>
                    <td>{{ stu.absences }}</td>
                    <td>{{ stu.G3 }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<h2>添加学生</h2>
<!-- 添加学生表单 -->
<form method="post" action="{% url 'Students:add_student' %}">
    {% csrf_token %}
    <div class="add-student-form">
        <label for="Stu_Number">学生学号:</label>
        <input type="text" name="Stu_Number" id="Stu_Number" title="学生学号">

        <label for="Class_Number_id">班级号:</label>
        <input type="text" name="Class_Number_id" id="Class_Number_id" title="班级号">

        <label for="Medu">母亲教育程度:</label>
        <input type="text" name="Medu" id="Medu" title="Medu-母亲的教育程度: 0 -无; 1 -小学教育; 2 -初中教育; 3 -高中教育; 4 –高等教育">

        <label for="Fedu">父亲教育程度:</label>
        <input type="text" name="Fedu" id="Fedu" title="Fedu-父亲的教育程度: 0 -无; 1 -小学教育; 2 -初中教育; 3 -高中教育; 4 –高等教育">

        <label for="traveltime">上学通勤时间:</label>
        <input type="text" name="traveltime" id="traveltime" title="Travel Time-上学通勤时间: 1 -&lt;15min; 2 -15至30min; 3 -30min至1h; 4 -&gt;1h">

        <label for="studytime">每周学习时间:</label>
        <input type="text" name="studytime" id="studytime" title="Study Time-每周学习时间: 1 -&lt;2h; 2 -2至5h; 3 -5至10h; 4 -&gt;10h">

        <label for="failures">失败次数:</label>
        <input type="text" name="failures" id="failures" title="Failures-课堂失败次数: 0至3; 4次以上均为4">
   
        <label for="famrel">家庭关系:</label>
        <input type="text" name="famrel" id="famrel" title="Famrel-家庭关系质量: 1 -非常差 至 5 -极好">
        
        <label for="freetime">空闲时间:</label>
        <input type="text" name="freetime" id="freetime" title="Freetime-空闲时间: 1 -极少 至 5 -极多">
        
        <label for="goout">出门时间:</label>
        <input type="text" name="goout" id="goout" title="Go out-外出时间: 1 -极少 至 5 -极多">
       
        <label for="healths">健康状况:</label>
        <input type="text" name="healths" id="healths" title="Health-健康状况: 1 -非常差 至 5 -极好">
        
        <label for="absences">缺勤次数:</label>
        <input type="text" name="absences" id="absences" title="Absences-缺勤次数">

        <label for="G3">成绩:</label>
        <input type="text" name="G3" id="G3" title="成绩">
    </div>
    <p><input type="submit" value="添加"></p>
</form>

<!-- <div class="pagination">
        {% if stus.has_previous %}
            <a href="?page=1">First</a>
            <a href="?page={{ stus.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">Page {{ stus.number }} of {{ stus.paginator.num_pages }}.</span>
        {% if stus.has_next %}
            <a href="?page={{ stus.next_page_number }}">Next</a>
            <a href="?page={{ stus.paginator.num_pages }}">Last</a>
        {% endif %}
</div>-->   
    
{% endblock %}